"""update camera model

Revision ID: 6226b0698302
Revises: 239b1283b2d4
Create Date: 2026-07-09 09:41:25.669023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6226b0698302'
down_revision: Union[str, Sequence[str], None] = '239b1283b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camera_type', sa.String(length=30), nullable=False))
    op.add_column('cameras', sa.Column('resolution', sa.String(length=20), nullable=False))
    op.add_column('cameras', sa.Column('fps', sa.Integer(), nullable=False))
    op.add_column('cameras', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('cameras', sa.Column('is_recording', sa.Boolean(), nullable=False))
    op.add_column('cameras', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('cameras', 'camera_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_constraint(op.f('cameras_station_id_fkey'), 'cameras', type_='foreignkey')
    op.create_foreign_key(None, 'cameras', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.create_foreign_key(op.f('cameras_station_id_fkey'), 'cameras', 'stations', ['station_id'], ['id'])
    op.alter_column('cameras', 'camera_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('cameras', 'last_seen')
    op.drop_column('cameras', 'is_recording')
    op.drop_column('cameras', 'status')
    op.drop_column('cameras', 'fps')
    op.drop_column('cameras', 'resolution')
    op.drop_column('cameras', 'camera_type')
    # ### end Alembic commands ###
